//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paye.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Comments", Schema = "dbo")]
    public partial class Comment
    {
        [Key]
        public long Id { get; set; }
        public /*Nullable<long>*/string userId { get; set; }
        public Nullable<System.Guid> postId { get; set; }
        public string userName { get; set; }
        public string comment { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
