//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paye.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Posts", Schema = "dbo")]
    public partial class Post
    {
        public Post()
        {
            if (postId == null)
                postId = Guid.NewGuid();
        }
        [Key]
        public long Id { get; set; }
        public Nullable<System.Guid> postId { get; set; }
        public /*Nullable<long>*/string userId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int subject { get; set; }
        public int city { get; set; }
        public Nullable<bool> isImmediate { get; set; }
        public Nullable<bool> isWoman { get; set; }
        public string cost { get; set; }
        public string numberFollowers { get; set; }
        public string images { get; set; }
        public string tag { get; set; }
        public string phoneNumber { get; set; }
        public string link { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string applicants { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public Nullable<System.DateTime> timeToJoin { get; set; }
        public Nullable<byte> state { get; set; }
        public Nullable<byte> service { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }

        [NotMapped]
        public string PersianStartDate { get; set; }
        [NotMapped]
        public string PersianFinishDate { get; set; }
        [NotMapped]
        public string PersianDeadline { get; set; }

        public static byte State_Pay_Category = 1;
        public static byte State_Pay_Immadiate = 2;
        public static byte State_Pay_Vip = 3;
        public static byte State_Pay_Story = 4;
        public static byte State_Pay_Nardeban = 5;


        public static byte State_New = 1;

        public static byte State_Ok = 2;
        public static byte State_OkEdit = 5;

        public static byte State_Nok = 3;
        public static byte State_Edit = 4;
              
        public static byte State_NokEdit = 6;

        public static byte State_Delete_Successful = 7;                
        public static byte State_Cancel = 8;

        public static byte State_Correction1 = 9;
        public static byte State_Correction2 = 10;
        public static byte State_Correction3 = 11;
        public static byte State_Correction4 = 12;

        public static byte State_Delete_otherway = 20;
        public static byte State_Delete_wentGood = 21;
        public static byte State_Auth_mobile = 22;
    }
}
