//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int Id { get; set; }
        public char sms { get; set; }
        public /*long*/string userId { get; set; }
        public DateTime createdate { get; set; }
        
    }
}
