//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paye.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Support", Schema = "dbo")]
    public partial class Support
    {
        [Key]
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
    }
}
