//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paye.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity;

    [Table("Users", Schema = "dbo")]
    public partial class User : IdentityUser
    {
        public User()
        {
            if (UserId == null)
                UserId = Guid.NewGuid();
        }
        //public string DisplayName { get; set; }

        //public string Avatar { get; set; }

        public virtual ICollection<Room> Rooms { get; set; }

        public virtual ICollection<Message> Messages { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User> manager, string authenticationType)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, authenticationType);
            // Add custom user claims here
            return userIdentity;
        }


        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }

        //[Key]
        //public long Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Age { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsShowMobile { get; set; }
        public string City { get; set; }
        public string ProfileImage { get; set; }
        public string Token { get; set; }
        public Nullable<bool> IsAuthenticate { get; set; }
        public Nullable<bool> IsMobileAuthenticate { get; set; }
        public string ServicesIds { get; set; }
        public string Telegram { get; set; }
        public string Soroosh { get; set; }
        public string Instagram { get; set; }
        public string Gmail { get; set; }
        public string Favorites { get; set; }
        public string AboutMe { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [NotMapped]
        public string TrustedVoteCount { get; set; }
        [NotMapped]
        public string UserAge { get; set; }
        [NotMapped]
        public bool IsTrust { get; set; }
        [NotMapped]
        public string ActivityState { get; set; }
    }
}
